# This is a basic workflow to help you get started with Actions

name: Build Frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install Zip
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8.0'
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Installs Depot Tools
      # echo "${pwd}/depot_tools" >> $GITHUB_PATH
      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH
      # Build Devtools
      - name: Download Devtools
        run: |
          fetch devtools-frontend
          
      - name: Build Devtools
        run: |
          cd devtools-frontend
          npm run install-deps
          gn gen out/Default
          echo "is_debug=false" >> out/Default/args.gn
          autoninja -C out/Default
      - name: Zip Output
        run: |
          cd devtools-frontend/out/Default/gen
          zip -qq -r front_end.zip front_end
        
      - name: Upload front_end.zip
        uses: actions/upload-artifact@v2
        with:
          name: front_end
          path: devtools-frontend/out/Default/gen/front_end.zip
